name: Check pushed code

on: push

jobs:
  code_check:
    name: Check code
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Laravel env
      run: cp src/.env.ci src/.env

    - name: Init App
      run: make init

    - name: Run phpcs
      run: make phpcs